#jekyll serve --config _config-dev.yml

title: Hadashi's Portfolio
email: kasia@hadashi.online
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:  ""
blogurl:  "/blog"
url:      "http://localhost:4000"
cdn-url:  "http://localhost:3000"

incremental: true

collections:
  case-studies:
    output: true
    permalink: /:collection/:name
  blog:
    output: true
    permalink: /:collection/:name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: "post"
  - scope:
      path: ""  
    values:
      layout: "default"